# Generated by Django 3.1.3 on 2020-11-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='route',
        ),
        migrations.AddField(
            model_name='room',
            name='route',
            field=models.CharField(default='meet', editable=False, max_length=20),
        ),
    ]
