# Generated by Django 3.1.2 on 2020-10-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='app',
            old_name='my_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='my_order',
            new_name='order',
        ),
    ]
