# Generated by Django 3.1.2 on 2020-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20201004_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
