# Generated by Django 3.1.3 on 2020-11-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20201111_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='address',
            new_name='meet',
        ),
    ]
