# Generated by Django 3.1.2 on 2020-10-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20201004_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['order'], 'verbose_name_plural': '3. Apps'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['order'], 'verbose_name_plural': '1. Class Rooms'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name_plural': '2. Teachers'},
        ),
    ]
