# Generated by Django 3.1.3 on 2020-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_auto_20201112_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='meet',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=80, unique=True),
        ),
    ]
