# Generated by Django 3.1.2 on 2020-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_auto_20201005_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='(unknown last name)', max_length=200),
            preserve_default=False,
        ),
    ]
